### ISSUE TITLE
Create License

### ISSUE THREAD

**Issue by asche056** [crvs/KDTree#1]
I enjoyed this project.  I wanted to use your code for commercial purposes but you have no license attached to it.  I'm wondering if you would be able to attach a license with something reasonable?

**Comment by crvs** [comment]
Hi, as stated in the comments the code is based on the rosetta code page 
http://rosettacode.org/wiki/K-d_tree
so I'm not sure how it works in terms of licensing

**Comment by crvs** [comment]
Come to think of it I didn't use any of the code iself, just the algorithm, which is in the public domain, so that is a non-issue. Licensed.
