### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by ygmoon-git** [crvs/KDTree#14]
Thank you for your wonderful job!

I found a minor bug in "KDTree.cpp"

In line 279:
"pointVec nbhp{nbh->size()};" should be "pointVec nbhp(nbh->size());"

In line 288:
"indexArr nbhi{nbh->size()};" should be "indexArr nbhi(nbh->size());"

Thanks!

**Comment by crvs** [comment]
Thanks! patch 0c1570071c1aad2247a401217e6e4d224d4e232d should fix this :)
