### ISSUE TITLE
Declared function dist not implemented

### ISSUE THREAD

**Issue by MK-3PP** [crvs/KDTree#3]
[KDTree.hpp](https://github.com/crvs/KDTree/blob/master/KDTree.hpp) declares
```
inline double dist(const point_t &, const point_t &);
inline double dist(const KDNodePtr &, const KDNodePtr &);
```
but [KDTree.cpp](https://github.com/crvs/KDTree/blob/master/KDTree.cpp) implements
```
inline double dist2(const point_t &, const point_t &);
inline double dist2(const KDNodePtr &, const KDNodePtr &);
```
istead.

Either declare dist2 in header file or implement dist implementation file.

**Comment by crvs** [comment]
yeah that was a silly bug
